working registration with flirt step, bias correct change necessary
IBT-FMI/SAMRI pull request #11
Opened 2017-01-16 22:55 UTC by damaggu

2017-01-17 00:59 UTC, TheChymera commented on samri/optimization/registration.py
> +	flt = fsl.FLIRT(cost_func='corratio', dof = 6, searchr_x = [-180,180], searchr_y = [-180,180], searchr_z = [-180,180], force_scaling = True)
are `searchr_x` and friends the parameters that make the registration try to reorient the image?

2017-01-17 10:10 UTC, damaggu commented on samri/optimization/registration.py
> +	flt = fsl.FLIRT(cost_func='corratio', dof = 6, searchr_x = [-180,180], searchr_y = [-180,180], searchr_z = [-180,180], force_scaling = True)
yup

2017-01-17 13:59 UTC, TheChymera commented
I'm glad this worked out for you, and I think it's ok to pull it for the registration examples - but I would be reticent to use this in the pipeline. We would either have to create two pipelines just to accommodate for this, or further parameterize the Bruker pipeline to allow selection of FLIRT or ANTs. I think this is too much complexity atm, and ideally we would figure out how to do this in ANTs.

I think the people in [this thread](https://github.com/stnava/ANTs/issues/399#issuecomment-272841079) would be happy to help us figure out how to use their software to accieve similar or better performance as FNIRT. Actually, I think  [this commnt](https://github.com/stnava/ANTs/issues/399#issuecomment-272841079) already points out some `antsRegistration` inputs that would help acchieve the same effect. Hve you tested them?

2017-01-17 14:45 UTC, damaggu commented
Why not incorporate as boolean flag, which gets activated if by hand or automated in case source and template orientation are not equal? or maybe it works just fine before the ants registration? have you tried for your data?

The -r option is not a real solution, since it's a hand-written a priori transformation, hence the user would need to the transformation steps, in which case he/she could do it with fslorient/swapdim as well.

2017-01-17 15:22 UTC, TheChymera commented
ah, I see. I thought there was a way to tell FNIRT to automatically go through all alternate registrations (it's just 8, I believe) and pick the best one. As such I feel the advantage this has over ANTs grows increasingly dim - this is basically what one could do with nibabel/(fslswapdim+fslorient) + ANTs

2017-01-17 15:28 UTC, damaggu commented
no, the hardcoded part i was talking about was the -r option with antsRegistration. Flirt goes automatically through all angles

2017-01-17 15:52 UTC, TheChymera commented
hm. uncool on the part of ANTs - so you think we can use FNIRT just to reorient the image? I really like ANTs and its interface, plus we finally managed to agree on it as a quasi-standard for the AIC.

But until ANTs gets this capability I really like the idea of your hand/automagically activated node - especially if we can keep all the transformations except this reorienting done in ANTs.

2017-01-17 15:54 UTC, TheChymera commented
But it's a bit non-trivial to integrate complex logic into nipype. I still think we should ask the ANTs people a few more times before we go down that route.

2017-01-17 16:08 UTC, damaggu commented
flirt could serve as initial rigid transform in front of ants, it works with 6 dof. no logic

2017-01-17 16:45 UTC, TheChymera commented on samri/optimization/registration.py
>  def structural_rigid_affine(template="/Users/marksm/GitHub/mriPipeline/ants_test/template4.nii.gz",
Looking good - so this function here now uses FLIRT for the reorient, and ANTs for everything else? Perhaps we should edit the name accordingly? and add a short docstring stating as much?

2017-01-17 16:46 UTC, TheChymera requested changes

2017-01-17 16:46 UTC, TheChymera commented on samri/optimization/registration.py
> +def structural_flirt_affine(template="/Users/marksm/GitHub/mriPipeline/ants_test/template4.nii.gz",
and this function here uses FLIRT for all things linear? Again, maybe a more descriptive name and/or a docstring?

2017-01-21 11:40 UTC, damaggu commented on samri/optimization/registration.py
>  def structural_rigid_affine(template="/Users/marksm/GitHub/mriPipeline/ants_test/template4.nii.gz",
I changed it accordingly. The function name is now structural_rigid_flirt_nonlin_syn, with added docstring. I've been playing with the parameters a little. Now it works really well for me. 

Could you try on your data?

2017-01-21 13:50 UTC, merged

2017-01-21 19:09 UTC, damaggu commented
how does the function work for your files, did you test it?

2017-01-22 00:27 UTC, TheChymera commented
not yet, as I do not have a mouse T2 atlas. I am really having trouble finding one. Could you maybe help me? Dis the resource where you found the rat atlas also have something for mice?

2017-01-25 10:01 UTC, damaggu commented
would this one work? https://scalablebrainatlas.incf.org/mouse/WHS12

2017-01-25 10:02 UTC, damaggu commented
otherwise i found mine here: https://scalablebrainatlas.incf.org/main/index.php?

2017-01-25 15:19 UTC, TheChymera commented
I haven't been able to access the original data in full resolutions  - I believe this is the link https://civmvoxport.duhs.duke.edu/voxbase/login.php?return_url=%2Fvoxbase%2Fstudyhome.php%3Fstudyid%3D132

But I did download one of the downsized templates, and it's not really that cool. Most of the interesting extra-cerebral features are cropped, and the template is not really regularly shaped/oriented:

![screenshot from 2017-01-25 16-14-16](https://cloud.githubusercontent.com/assets/950524/22296282/ee058d9e-e319-11e6-9e92-f5051ca90eb8.png)


I'd really like to get ahold of the second atlas listed here - but I can't seem to get through to these researchers: https://wiki.mouseimaging.ca/display/MICePub/Mouse+Brain+Atlases