fixed connectivity plot, fixed atlas labels
IBT-FMI/SAMRI pull request #31
Opened 2017-07-20 19:32 UTC by damaggu

2017-07-21 16:23 UTC, TheChymera requested changes

2017-07-21 16:23 UTC, TheChymera commented on samri/plotting/examples.py
> +	labels = '/Users/marksm/GitHub/mriPipeline/restingState/von_christian/labels.csv',
We need to develop a more unified datapath - are you sure you can't keep your SAMRI-related data under `/Users/marks/ni_data/` (I assume under MacOS, `~` evaluates to `/Users/marks`). If not, could you at least set up a symlink?

Ideally, further down the line, we will be [distributing example data in a standardized path](https://github.com/IBT-FMI/SAMRI/issues/25) for the examples, but until then, I think the best approach, is for all developers to use analogous data paths.

2017-07-21 16:23 UTC, TheChymera commented on samri/pipelines/fc.py
> +	save_csv = True,
`save_as` is better than `save_csv`. Ideally we allow the format to be determined from the string value wherever possible.

2017-07-24 16:44 UTC, damaggu commented
fixed, could you test?

2017-07-24 16:54 UTC, TheChymera approved these changes

2017-07-24 16:54 UTC, merged