3Dplot
IBT-FMI/SAMRI pull request #73
Opened 2018-11-21 11:33 UTC by setina42

2018-12-06 13:39 UTC, TheChymera requested changes

2018-12-06 13:39 UTC, TheChymera commented on samri/plotting/maps.py
> +	template="~/usr/shared/mouse-brain-atlases/ambmc2dsurqec_15micron_cut_mesh_1_decimated.obj",
This is not under the user home dir. This is a system-wide directory, also it is called `/usr/share`, without the “d”.

2018-12-15 22:15 UTC, TheChymera commented
@setina42 is this still in sync with the updates you made as part of https://github.com/nilearn/nilearn/pull/1869 ?

2018-12-15 22:29 UTC, setina42 commented
@TheChymera Yes, this is still in sync.

2018-12-15 23:02 UTC, merged

2018-12-15 23:02 UTC, TheChymera commented
thanks :)